In [1]:
import numpy as np

In [2]:
import urllib

In [3]:
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"

In [4]:
raw_data = urllib.urlopen(url)

In [5]:
dataset = np.loadtxt(raw_data, delimiter=',')

In [6]:
X = dataset[:,0:7]

In [7]:
y = dataset[:,8]

In [8]:
from sklearn import preprocessing

In [9]:
X

array([[   6.   ,  148.   ,   72.   , ...,    0.   ,   33.6  ,    0.627],
       [   1.   ,   85.   ,   66.   , ...,    0.   ,   26.6  ,    0.351],
       [   8.   ,  183.   ,   64.   , ...,    0.   ,   23.3  ,    0.672],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,  112.   ,   26.2  ,    0.245],
       [   1.   ,  126.   ,   60.   , ...,    0.   ,   30.1  ,    0.349],
       [   1.   ,   93.   ,   70.   , ...,    0.   ,   30.4  ,    0.315]])

In [10]:
normalized_X = preprocessing.normalize(X)

In [11]:
normalized_X

array([[ 0.03494617,  0.86200564,  0.41935409, ...,  0.        ,
         0.19569858,  0.00365188],
       [ 0.00872683,  0.74178025,  0.57597054, ...,  0.        ,
         0.23213358,  0.00306312],
       [ 0.04093566,  0.93640332,  0.32748532, ...,  0.        ,
         0.11922512,  0.0034386 ],
       ..., 
       [ 0.02727338,  0.66001582,  0.39273669, ...,  0.61092373,
         0.14291252,  0.0013364 ],
       [ 0.0070043 ,  0.8825414 ,  0.42025781, ...,  0.        ,
         0.21082934,  0.0024445 ],
       [ 0.00804902,  0.74855891,  0.56343144, ...,  0.        ,
         0.24469022,  0.00253544]])

In [12]:
standardized_X = preprocessing.scale(X)

In [13]:
standardized_X

array([[ 0.63994726,  0.84832379,  0.14964075, ..., -0.69289057,
         0.20401277,  0.46849198],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.69289057,
        -0.68442195, -0.36506078],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -0.69289057,
        -1.10325546,  0.60439732],
       ..., 
       [ 0.3429808 ,  0.00330087,  0.14964075, ...,  0.27959377,
        -0.73518964, -0.68519336],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.69289057,
        -0.24020459, -0.37110101],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.69289057,
        -0.20212881, -0.47378505]])

In [14]:
from sklearn import metrics

In [15]:
from sklearn.ensemble import ExtraTreesClassifier

In [28]:
model = ExtraTreesClassifier()

In [29]:
model.fit(X,y)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [30]:
print model.feature_importances_

[ 0.13468461  0.26041197  0.12122264  0.09821195  0.07615845  0.16281593
  0.14649443]


In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
model = LogisticRegression()

In [21]:
model.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
print model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [23]:
expected = y

In [24]:
predicted = model.predict(X)

In [26]:
print metrics.classification_report(expected, predicted)

             precision    recall  f1-score   support

        0.0       0.79      0.89      0.84       500
        1.0       0.74      0.55      0.63       268

avg / total       0.77      0.77      0.77       768



In [33]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print metrics.classification_report(expected, predicted)
print metrics.confusion_matrix(expected, predicted)

GaussianNB()
             precision    recall  f1-score   support

        0.0       0.80      0.86      0.83       500
        1.0       0.69      0.60      0.64       268

avg / total       0.76      0.77      0.76       768

[[429  71]
 [108 160]]
